baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Travel Site"
theme = "ananke"
paginate = 5

# Main menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
