backend:
  name: github
  repo: sajad-zamani88/travel-in-usa
  branch: main
  base_url: https://travel-in-usa-auth.sajadzamani88.workers.dev
  auth_endpoint: auth
  client_id: "YOUR_GITHUB_CLIENT_ID"        # مرحله 3: از GitHub App کپی کن
  client_secret: "4f4140ec70ff9e5679074174321b6034b2cefc10" # مرحله 3: از GitHub App کپی کن
  #identity_url: https://your-site.netlify.app/.netlify/identity  # بعد از فعال‌سازی Identity
  # برای GitHub auth نیاز به Netlify Identity

media_folder: "static/images"   # فولدر ذخیره تصاویر
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Hero Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Meta Description", name: "description", widget: "string" }
      - { label: "Meta Keywords", name: "keywords", widget: "list" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Meta Description", name: "description", widget: "string" }
